### PR TITLE
Simplify config and accomodate fedora

### PR DESCRIPTION
**Pull request by digikar99**
We could avoid a good chunk of the intermediate parsing and unparsing of the config variables, while also being able to accomodate more systems.

### CODE REVIEW

**Comment by digikar99** [comment]
@plandes, could you please review the config-darwin.lisp corresponding to the newly simplified configuration format?

**Comment by digikar99** [comment]
For the moment, I have merged this without checking on Mac OS since some users would appreciate an early fix. In case there's an issue on Mac OS, feel free to raise another PR!

**Comment by plandes** [comment]
@digikar99 I currently have a modified version of the code base to suit my needs (I submitted a pull request that has not been yet folded in). Things are busy, but when it slow down I will test and submit any necessary pull request. Thank you for your patience.

**Comment by digikar99** [comment]
@plandes Yes, that sounds good. Thank you for testing and contributing!

**Pull request merged**
